version: '2.26.1'

services:
  composition:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=database

  database:
    image: mysql:8.0.37
    container_name: mysql-composer-composition
    ports:
      - "3306:3306"
    networks:
      - composition
    environment:
      - MYSQL_DATABASE=db_composition
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=admin
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 100
    volumes:
      - .\DbData:/var/lib/mysql
