version: '2.26.1'

services:
  composition:
    build: .
    mem_limit: 512m
    networks:
      - composition_network
    ports:
      - "8080:8080"
    hostname: composition-microservice
    depends_on:
      composition_database:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=composition-database

  composition_database:
    image: mysql:8.0.37
    container_name: mysql-composer-composition
    networks:
      - composition_network
    hostname: composition-database
    environment:
      - MYSQL_DATABASE=db_composition
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=admin
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 100
    volumes:
      - .\DbData:/var/lib/mysql

networks:
  composition_network: {}